// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqexpujpjfiyqygtcxbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xZXhwdWpwamZpeXF5Z3RjeGJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNzAwMTcsImV4cCI6MjA1Njc0NjAxN30.z7G4eOAfZDoYuKsV8cByGpjukXUYRiY3N479XuciOig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);